services:
  - type: web
    name: bulk-emailer
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir --prefer-binary -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_APP_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"